name: Mount Fuji Availability Watcher

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # lets you run manually too

jobs:
  check-availability:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up headless Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run availability watcher
        run: python availability_watcher.py
