name: Mount Fuji Availability Watcher

on:
  schedule:
    - cron: '0 * * * *'   # Every hour at 00 minutes past the hour
  workflow_dispatch:       # Manual run

jobs:
  check-availability:
    runs-on: ubuntu-latest

    env:
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      GITHUB_ACTIONS: true   # let script know we're inside GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up headless Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run availability watcher
        run: python availability_watcher.py
